% Produtos e preços em cada supermercado
produto(mercadoDoPovo, arroz, 5.00).
produto(mercadoDoPovo, feijao, 4.00).
produto(mercadoDoPovo, leite, 3.00).
produto(mercadoDoPovo, cafe, 7.00).
produto(mercadoDoPovo, acucar, 3.50).
produto(mercadoDoPovo, manteiga, 4.50).
produto(mercadoDoPovo, macarrao, 3.20).
produto(mercadoDoPovo, carne, 25.00).
produto(mercadoDoPovo, pao, 5.80).
produto(mercadoDoPovo, tomate, 4.00).
produto(mercadoDoPovo, ovos, 6.70).
produto(mercadoDoPovo, queijo, 8.20).
produto(mercadoDoPovo, laranja, 3.90).
produto(mercadoDoPovo, abacaxi, 5.50).
produto(mercadoDoPovo, abobora, 5.80).
produto(mercadoDoPovo, alface, 3.00).
produto(mercadoDoPovo, cenoura, 2.50).
produto(mercadoDoPovo, batata, 4.20).
produto(mercadoDoPovo, oleo, 6.00).
produto(mercadoDoPovo, cebola, 2.80).
produto(mercadoDoPovo, sal, 1.20).
produto(mercadoDoPovo, alho, 2.50).
produto(mercadoDoPovo, pimentao, 3.00).
produto(mercadoDoPovo, peixe, 18.00).
produto(mercadoDoPovo, frango, 12.00).
produto(mercadoDoPovo, linguiça, 9.00).
produto(mercadoDoPovo, polvilho_doce, 7.00).
produto(mercadoDoPovo, queijo_minas, 15.00).
produto(mercadoDoPovo, farinha, 4.50).
produto(mercadoDoPovo, acucar, 3.00).
produto(mercadoDoPovo, chocolate, 5.00).
produto(mercadoDoPovo, cenoura, 2.80).
produto(mercadoDoPovo, batata, 4.20).
produto(mercadoDoPovo, agua, 1.00).
produto(mercadoDoPovo, leite_condensado, 4.00).
produto(mercadoDoPovo, chocolate_po, 3.50).
produto(mercadoDoPovo, granulado, 2.50).
produto(mercadoDoPovo, massa_folhada, 6.00).
produto(mercadoDoPovo, alho_poro, 3.50).
produto(mercadoDoPovo, creme_leite, 3.00).
produto(mercadoDoPovo, carne_moida, 22.00).
produto(mercadoDoPovo, frango_desfiado, 14.00).
produto(mercadoDoPovo, milho, 2.20).
produto(mercadoDoPovo, ervilha, 2.00).
produto(mercadoDoPovo, caldo_galinha, 1.50).
produto(mercadoDoPovo, farinha_trigo, 3.00).
produto(mercadoDoPovo, farofa, 4.00).
produto(mercadoDoPovo, coco_ralado, 3.50).
produto(mercadoDoPovo, acucar, 2.00).
produto(mercadoDoPovo, salsa, 1.80).
produto(mercadoDoPovo, maracuja, 6.00).
produto(mercadoDoPovo, gelatina, 2.50).
produto(mercadoDoPovo, mandioca, 2.50).
produto(mercadoDoPovo, queijo_parmesao, 10.00).
produto(mercadoDoPovo, arroz_arboreo, 6.00).
produto(mercadoDoPovo, cogumelos, 12.00).
produto(mercadoDoPovo, caldo_legumes, 2.50).
produto(mercadoDoPovo, massa_lasanha, 7.00).
produto(mercadoDoPovo, presunto, 6.00).
produto(mercadoDoPovo, palmito, 5.00).
produto(mercadoDoPovo, sardinha, 4.00).
produto(mercadoDoPovo, pao, 2.50).
produto(mercadoDoPovo, leite_de_coco, 3.00).
produto(mercadoDoPovo, azeite_de_dende, 5.50).
produto(mercadoDoPovo, camarão, 18.00).
produto(mercadoDoPovo, amendoim, 7.00).

produto(mercadoBomPreco, arroz, 4.50).
produto(mercadoBomPreco, feijao, 3.50).
produto(mercadoBomPreco, leite, 3.50).
produto(mercadoBomPreco, carne, 24.00).
produto(mercadoBomPreco, pao, 5.50).
produto(mercadoBomPreco, acucar, 3.20).
produto(mercadoBomPreco, tomate, 4.00).
produto(mercadoBomPreco, manteiga, 4.60).
produto(mercadoBomPreco, cafe, 7.10).
produto(mercadoBomPreco, ovos, 6.90).
produto(mercadoBomPreco, queijo, 8.10).
produto(mercadoBomPreco, macarrao, 3.40).
produto(mercadoBomPreco, laranja, 3.80).
produto(mercadoBomPreco, abacaxi, 5.00).
produto(mercadoBomPreco, alface, 3.20).
produto(mercadoBomPreco, cenoura, 2.60).
produto(mercadoBomPreco, batata, 4.00).
produto(mercadoBomPreco, oleo, 5.80).
produto(mercadoBomPreco, cebola, 2.70).
produto(mercadoBomPreco, sal, 1.10).
produto(mercadoBomPreco, alho, 2.40).
produto(mercadoBomPreco, pimentao, 2.90).
produto(mercadoBomPreco, peixe, 17.80).
produto(mercadoBomPreco, frango, 11.80).
produto(mercadoBomPreco, linguiça, 8.80).
produto(mercadoBomPreco, polvilho_doce, 6.80).
produto(mercadoBomPreco, queijo_minas, 14.80).
produto(mercadoBomPreco, farinha, 4.40).
produto(mercadoBomPreco, chocolate, 4.80).
produto(mercadoBomPreco, leite_condensado, 3.80).
produto(mercadoBomPreco, chocolate_po, 3.40).
produto(mercadoBomPreco, granulado, 2.40).
produto(mercadoBomPreco, massa_folhada, 5.80).
produto(mercadoBomPreco, alho_poro, 3.40).
produto(mercadoBomPreco, creme_leite, 2.80).
produto(mercadoBomPreco, carne_moida, 21.80).
produto(mercadoBomPreco, frango_desfiado, 13.80).
produto(mercadoBomPreco, milho, 2.10).
produto(mercadoBomPreco, ervilha, 1.90).
produto(mercadoBomPreco, caldo_galinha, 1.40).
produto(mercadoBomPreco, farinha_trigo, 2.90).
produto(mercadoBomPreco, farofa, 3.90).
produto(mercadoBomPreco, coco_ralado, 3.40).
produto(mercadoBomPreco, acucar, 1.90).
produto(mercadoBomPreco, salsa, 1.70).
produto(mercadoBomPreco, maracuja, 5.80).
produto(mercadoBomPreco, gelatina, 2.40).
produto(mercadoBomPreco, mandioca, 2.40).
produto(mercadoBomPreco, queijo_parmesao, 9.80).
produto(mercadoBomPreco, arroz_arboreo, 5.80).
produto(mercadoBomPreco, cogumelos, 11.80).
produto(mercadoBomPreco, caldo_legumes, 2.40).
produto(mercadoBomPreco, massa_lasanha, 6.80).
produto(mercadoBomPreco, presunto, 5.80).
produto(mercadoBomPreco, palmito, 4.80).
produto(mercadoBomPreco, sardinha, 3.80).
produto(mercadoBomPreco, pao, 2.40).
produto(mercadoBomPreco, leite_de_coco, 2.80).
produto(mercadoBomPreco, azeite_de_dende, 5.40).
produto(mercadoBomPreco, camarão, 17.80).
produto(mercadoBomPreco, amendoim, 6.80).

produto(mercadoEconomico, arroz, 4.50).
produto(mercadoEconomico, feijao, 4.50).
produto(mercadoEconomico, leite, 2.50).
produto(mercadoEconomico, carne, 26.00).
produto(mercadoEconomico, pao, 6.50).
produto(mercadoEconomico, manteiga, 4.70).
produto(mercadoEconomico, cafe, 7.20).
produto(mercadoEconomico, macarrao, 3.50).
produto(mercadoEconomico, abobora, 5.70).
produto(mercadoEconomico, laranja, 3.90).
produto(mercadoEconomico, alface, 3.10).
produto(mercadoEconomico, cenoura, 2.70).
produto(mercadoEconomico, batata, 4.10).
produto(mercadoEconomico, tomate, 4.20).
produto(mercadoEconomico, ovos, 7.00).
produto(mercadoEconomico, queijo, 8.50).
produto(mercadoEconomico, oleo, 6.10).
produto(mercadoEconomico, cebola, 2.90).
produto(mercadoEconomico, sal, 1.30).
produto(mercadoEconomico, alho, 2.60).
produto(mercadoEconomico, pimentao, 3.10).
produto(mercadoEconomico, peixe, 18.20).
produto(mercadoEconomico, frango, 12.20).
produto(mercadoEconomico, linguiça, 9.20).
produto(mercadoEconomico, polvilho_doce, 7.20).
produto(mercadoEconomico, queijo_minas, 15.20).
produto(mercadoEconomico, farinha, 4.70).
produto(mercadoEconomico, chocolate, 5.20).
produto(mercadoEconomico, leite_condensado, 4.20).
produto(mercadoEconomico, chocolate_po, 3.60).
produto(mercadoEconomico, granulado, 2.60).
produto(mercadoEconomico, massa_folhada, 6.20).
produto(mercadoEconomico, alho_poro, 3.60).
produto(mercadoEconomico, creme_leite, 3.20).
produto(mercadoEconomico, carne_moida, 22.20).
produto(mercadoEconomico, frango_desfiado, 14.20).
produto(mercadoEconomico, milho, 2.30).
produto(mercadoEconomico, ervilha, 2.10).
produto(mercadoEconomico, caldo_galinha, 1.60).
produto(mercadoEconomico, farinha_trigo, 3.10).
produto(mercadoEconomico, farofa, 4.20).
produto(mercadoEconomico, coco_ralado, 3.60).
produto(mercadoEconomico, acucar, 2.10).
produto(mercadoEconomico, salsa, 1.90).
produto(mercadoEconomico, maracuja, 6.20).
produto(mercadoEconomico, gelatina, 2.60).
produto(mercadoEconomico, mandioca, 2.60).
produto(mercadoEconomico, queijo_parmesao, 10.20).
produto(mercadoEconomico, arroz_arboreo, 6.20).
produto(mercadoEconomico, cogumelos, 12.20).
produto(mercadoEconomico, caldo_legumes, 2.60).
produto(mercadoEconomico, massa_lasanha, 7.20).
produto(mercadoEconomico, presunto, 6.20).
produto(mercadoEconomico, palmito, 5.20).
produto(mercadoEconomico, sardinha, 4.20).
produto(mercadoEconomico, pao, 2.60).
produto(mercadoEconomico, leite_de_coco, 3.20).
produto(mercadoEconomico, azeite_de_dende, 5.60).
produto(mercadoEconomico, camarão, 18.20).
produto(mercadoEconomico, amendoim, 7.20).

produto(mercadoPopular, arroz, 4.80).
produto(mercadoPopular, feijao, 3.80).
produto(mercadoPopular, leite, 3.20).
produto(mercadoPopular, carne, 25.50).
produto(mercadoPopular, pao, 6.20).
produto(mercadoPopular, ovos, 7.00).
produto(mercadoPopular, queijo, 8.00).
produto(mercadoPopular, tomate, 4.10).
produto(mercadoPopular, cafe, 7.30).
produto(mercadoPopular, acucar, 3.60).
produto(mercadoPopular, manteiga, 4.80).
produto(mercadoPopular, macarrao, 3.60).
produto(mercadoPopular, laranja, 4.00).
produto(mercadoPopular, abacaxi, 5.40).
produto(mercadoPopular, abobora, 5.90).
produto(mercadoPopular, alface, 3.20).
produto(mercadoPopular, cenoura, 2.80).
produto(mercadoPopular, batata, 4.30).
produto(mercadoPopular, oleo, 5.90).
produto(mercadoPopular, cebola, 2.80).
produto(mercadoPopular, sal, 1.20).
produto(mercadoPopular, alho, 2.50).
produto(mercadoPopular, pimentao, 3.00).
produto(mercadoPopular, peixe, 18.00).
produto(mercadoPopular, frango, 12.00).
produto(mercadoPopular, linguiça, 9.00).
produto(mercadoPopular, polvilho_doce, 7.00).
produto(mercadoPopular, queijo_minas, 15.00).
produto(mercadoPopular, farinha, 4.50).
produto(mercadoPopular, chocolate, 5.00).
produto(mercadoPopular, leite_condensado, 4.00).
produto(mercadoPopular, chocolate_po, 3.50).
produto(mercadoPopular, granulado, 2.50).
produto(mercadoPopular, massa_folhada, 6.00).
produto(mercadoPopular, alho_poro, 3.50).
produto(mercadoPopular, creme_leite, 3.00).
produto(mercadoPopular, carne_moida, 22.00).
produto(mercadoPopular, frango_desfiado, 14.00).
produto(mercadoPopular, milho, 2.20).
produto(mercadoPopular, ervilha, 2.00).
produto(mercadoPopular, caldo_galinha, 1.50).
produto(mercadoPopular, farinha_trigo, 3.00).
produto(mercadoPopular, farofa, 4.00).
produto(mercadoPopular, coco_ralado, 3.50).
produto(mercadoPopular, acucar, 2.00).
produto(mercadoPopular, salsa, 1.80).
produto(mercadoPopular, maracuja, 6.00).
produto(mercadoPopular, gelatina, 2.50).
produto(mercadoPopular, mandioca, 2.50).
produto(mercadoPopular, queijo_parmesao, 10.00).
produto(mercadoPopular, arroz_arboreo, 6.00).
produto(mercadoPopular, cogumelos, 12.00).
produto(mercadoPopular, caldo_legumes, 2.50).
produto(mercadoPopular, massa_lasanha, 7.00).
produto(mercadoPopular, presunto, 6.00).
produto(mercadoPopular, palmito, 5.00).
produto(mercadoPopular, sardinha, 4.00).
produto(mercadoPopular, pao, 2.50).
produto(mercadoPopular, leite_de_coco, 3.00).
produto(mercadoPopular, azeite_de_dende, 5.50).
produto(mercadoPopular, camarão, 18.00).
produto(mercadoPopular, amendoim, 7.00).

produto(mercadoSaoJoao, arroz, 4.30).
produto(mercadoSaoJoao, feijao, 3.30).
produto(mercadoSaoJoao, leite, 3.10).
produto(mercadoSaoJoao, carne, 24.50).
produto(mercadoSaoJoao, pao, 5.80).
produto(mercadoSaoJoao, queijo, 8.00).
produto(mercadoSaoJoao, manteiga, 4.40).
produto(mercadoSaoJoao, acucar, 3.60).
produto(mercadoSaoJoao, cafe, 7.20).
produto(mercadoSaoJoao, macarrao, 3.50).
produto(mercadoSaoJoao, tomate, 4.20).
produto(mercadoSaoJoao, ovos, 7.10).
produto(mercadoSaoJoao, abobora, 5.80).
produto(mercadoSaoJoao, laranja, 3.80).
produto(mercadoSaoJoao, alface, 3.30).
produto(mercadoSaoJoao, cenoura, 2.90).
produto(mercadoSaoJoao, batata, 4.20).
produto(mercadoSaoJoao, oleo, 5.70).
produto(mercadoSaoJoao, cebola, 2.60).
produto(mercadoSaoJoao, sal, 1.10).
produto(mercadoSaoJoao, alho, 2.40).
produto(mercadoSaoJoao, pimentao, 2.80).
produto(mercadoSaoJoao, peixe, 17.70).
produto(mercadoSaoJoao, frango, 11.70).
produto(mercadoSaoJoao, linguiça, 8.70).
produto(mercadoSaoJoao, polvilho_doce, 6.70).
produto(mercadoSaoJoao, queijo_minas, 14.70).
produto(mercadoSaoJoao, farinha, 4.40).
produto(mercadoSaoJoao, chocolate, 4.90).
produto(mercadoSaoJoao, leite_condensado, 3.90).
produto(mercadoSaoJoao, chocolate_po, 3.40).
produto(mercadoSaoJoao, granulado, 2.40).
produto(mercadoSaoJoao, massa_folhada, 5.90).
produto(mercadoSaoJoao, alho_poro, 3.40).
produto(mercadoSaoJoao, creme_leite, 2.90).
produto(mercadoSaoJoao, carne_moida, 21.90).
produto(mercadoSaoJoao, frango_desfiado, 13.90).
produto(mercadoSaoJoao, milho, 2.20).
produto(mercadoSaoJoao, ervilha, 2.00).
produto(mercadoSaoJoao, caldo_galinha, 1.50).
produto(mercadoSaoJoao, farinha_trigo, 3.00).
produto(mercadoSaoJoao, farofa, 4.10).
produto(mercadoSaoJoao, coco_ralado, 3.40).
produto(mercadoSaoJoao, acucar, 1.90).
produto(mercadoSaoJoao, salsa, 1.70).
produto(mercadoSaoJoao, maracuja, 5.90).
produto(mercadoSaoJoao, gelatina, 2.40).
produto(mercadoSaoJoao, mandioca, 2.40).
produto(mercadoSaoJoao, queijo_parmesao, 9.90).
produto(mercadoSaoJoao, arroz_arboreo, 5.90).
produto(mercadoSaoJoao, cogumelos, 11.90).
produto(mercadoSaoJoao, caldo_legumes, 2.40).
produto(mercadoSaoJoao, massa_lasanha, 6.90).
produto(mercadoSaoJoao, presunto, 5.90).
produto(mercadoSaoJoao, palmito, 4.90).
produto(mercadoSaoJoao, sardinha, 3.90).
produto(mercadoSaoJoao, pao, 2.40).
produto(mercadoSaoJoao, leite_de_coco, 2.90).
produto(mercadoSaoJoao, azeite_de_dende, 5.30).
produto(mercadoSaoJoao, camarão, 17.70).
produto(mercadoSaoJoao, amendoim, 6.70).

produto(mercadoCentral, arroz, 4.20).
produto(mercadoCentral, feijao, 3.20).
produto(mercadoCentral, leite, 3.40).
produto(mercadoCentral, carne, 23.50).
produto(mercadoCentral, pao, 5.70).
produto(mercadoCentral, macarrao, 3.50).
produto(mercadoCentral, cafe, 7.10).
produto(mercadoCentral, ovos, 6.90).
produto(mercadoCentral, queijo, 8.00).
produto(mercadoCentral, acucar, 3.50).
produto(mercadoCentral, manteiga, 4.50).
produto(mercadoCentral, abobora, 5.70).
produto(mercadoCentral, laranja, 3.90).
produto(mercadoCentral, alface, 3.20).
produto(mercadoCentral, cenoura, 2.70).
produto(mercadoCentral, batata, 4.10).
produto(mercadoCentral, oleo, 5.80).
produto(mercadoCentral, cebola, 2.70).
produto(mercadoCentral, sal, 1.10).
produto(mercadoCentral, alho, 2.40).
produto(mercadoCentral, pimentao, 2.90).
produto(mercadoCentral, peixe, 17.90).
produto(mercadoCentral, frango, 11.90).
produto(mercadoCentral, linguiça, 8.90).
produto(mercadoCentral, polvilho_doce, 6.90).
produto(mercadoCentral, queijo_minas, 14.90).
produto(mercadoCentral, farinha, 4.50).
produto(mercadoCentral, chocolate, 4.80).
produto(mercadoCentral, leite_condensado, 3.80).
produto(mercadoCentral, chocolate_po, 3.40).
produto(mercadoCentral, granulado, 2.40).
produto(mercadoCentral, massa_folhada, 5.80).
produto(mercadoCentral, alho_poro, 3.40).
produto(mercadoCentral, creme_leite, 2.80).
produto(mercadoCentral, carne_moida, 21.90).
produto(mercadoCentral, frango_desfiado, 13.90).
produto(mercadoCentral, milho, 2.20).
produto(mercadoCentral, ervilha, 2.00).
produto(mercadoCentral, caldo_galinha, 1.50).
produto(mercadoCentral, farinha_trigo, 3.00).
produto(mercadoCentral, farofa, 3.90).
produto(mercadoCentral, coco_ralado, 3.40).
produto(mercadoCentral, acucar, 1.90).
produto(mercadoCentral, salsa, 1.70).
produto(mercadoCentral, maracuja, 5.80).
produto(mercadoCentral, gelatina, 2.40).
produto(mercadoCentral, mandioca, 2.40).
produto(mercadoCentral, queijo_parmesao, 9.80).
produto(mercadoCentral, arroz_arboreo, 5.80).
produto(mercadoCentral, cogumelos, 11.80).
produto(mercadoCentral, caldo_legumes, 2.40).
produto(mercadoCentral, massa_lasanha, 6.80).
produto(mercadoCentral, presunto, 5.80).
produto(mercadoCentral, palmito, 4.80).
produto(mercadoCentral, sardinha, 3.80).
produto(mercadoCentral, pao, 2.40).
produto(mercadoCentral, leite_de_coco, 2.80).
produto(mercadoCentral, azeite_de_dende, 5.40).
produto(mercadoCentral, camarão, 17.90).
produto(mercadoCentral, amendoim, 6.90).

produto(mercadoNovaEra, arroz, 4.20).
produto(mercadoNovaEra, feijao, 3.70).
produto(mercadoNovaEra, leite, 3.00).
produto(mercadoNovaEra, carne, 25.00).
produto(mercadoNovaEra, pao, 6.00).
produto(mercadoNovaEra, tomate, 4.00).
produto(mercadoNovaEra, abacaxi, 5.50).
produto(mercadoNovaEra, laranja, 4.10).
produto(mercadoNovaEra, queijo, 8.30).
produto(mercadoNovaEra, ovos, 7.00).
produto(mercadoNovaEra, manteiga, 4.60).
produto(mercadoNovaEra, cafe, 7.00).
produto(mercadoNovaEra, abobora, 5.60).
produto(mercadoNovaEra, alface, 3.20).
produto(mercadoNovaEra, cenoura, 2.60).
produto(mercadoNovaEra, batata, 4.20).
produto(mercadoNovaEra, acucar, 3.50).
produto(mercadoNovaEra, oleo, 5.90).
produto(mercadoNovaEra, cebola, 2.80).
produto(mercadoNovaEra, sal, 1.20).
produto(mercadoNovaEra, alho, 2.50).
produto(mercadoNovaEra, pimentao, 3.00).
produto(mercadoNovaEra, peixe, 18.10).
produto(mercadoNovaEra, frango, 12.10).
produto(mercadoNovaEra, linguiça, 9.10).
produto(mercadoNovaEra, polvilho_doce, 7.10).
produto(mercadoNovaEra, queijo_minas, 15.10).
produto(mercadoNovaEra, farinha, 4.60).
produto(mercadoNovaEra, chocolate, 5.10).
produto(mercadoNovaEra, leite_condensado, 4.10).
produto(mercadoNovaEra, chocolate_po, 3.50).
produto(mercadoNovaEra, granulado, 2.50).
produto(mercadoNovaEra, massa_folhada, 6.10).
produto(mercadoNovaEra, alho_poro, 3.50).
produto(mercadoNovaEra, creme_leite, 3.10).
produto(mercadoNovaEra, carne_moida, 22.10).
produto(mercadoNovaEra, frango_desfiado, 14.10).
produto(mercadoNovaEra, milho, 2.20).
produto(mercadoNovaEra, ervilha, 2.00).
produto(mercadoNovaEra, caldo_galinha, 1.50).
produto(mercadoNovaEra, farinha_trigo, 3.00).
produto(mercadoNovaEra, farofa, 4.00).
produto(mercadoNovaEra, coco_ralado, 3.50).
produto(mercadoNovaEra, acucar, 2.00).
produto(mercadoNovaEra, salsa, 1.80).
produto(mercadoNovaEra, maracuja, 6.10).
produto(mercadoNovaEra, gelatina, 2.50).
produto(mercadoNovaEra, mandioca, 2.50).
produto(mercadoNovaEra, queijo_parmesao, 10.10).
produto(mercadoNovaEra, arroz_arboreo, 6.10).
produto(mercadoNovaEra, cogumelos, 12.10).
produto(mercadoNovaEra, caldo_legumes, 2.50).
produto(mercadoNovaEra, massa_lasanha, 7.10).
produto(mercadoNovaEra, presunto, 6.10).
produto(mercadoNovaEra, palmito, 5.10).
produto(mercadoNovaEra, sardinha, 4.10).
produto(mercadoNovaEra, pao, 2.50).
produto(mercadoNovaEra, leite_de_coco, 3.10).
produto(mercadoNovaEra, azeite_de_dende, 5.50).
produto(mercadoNovaEra, camarão, 18.10).
produto(mercadoNovaEra, amendoim, 7.10).

produto(mercadoCidade, arroz, 4.20).
produto(mercadoCidade, feijao, 4.10).
produto(mercadoCidade, leite, 2.90).
produto(mercadoCidade, carne, 26.50).
produto(mercadoCidade, pao, 6.30).
produto(mercadoCidade, abacaxi, 5.00).
produto(mercadoCidade, acucar, 3.70).
produto(mercadoCidade, queijo, 8.10).
produto(mercadoCidade, ovos, 7.10).
produto(mercadoCidade, manteiga, 4.60).
produto(mercadoCidade, macarrao, 3.40).
produto(mercadoCidade, laranja, 3.90).
produto(mercadoCidade, alface, 3.30).
produto(mercadoCidade, cenoura, 2.80).
produto(mercadoCidade, batata, 4.00).
produto(mercadoCidade, cafe, 7.00).
produto(mercadoCidade, oleo, 6.00).
produto(mercadoCidade, cebola, 2.90).
produto(mercadoCidade, sal, 1.30).
produto(mercadoCidade, alho, 2.60).
produto(mercadoCidade, pimentao, 3.10).
produto(mercadoCidade, peixe, 18.30).
produto(mercadoCidade, frango, 12.30).
produto(mercadoCidade, linguiça, 9.30).
produto(mercadoCidade, polvilho_doce, 7.30).
produto(mercadoCidade, queijo_minas, 15.30).
produto(mercadoCidade, farinha, 4.70).
produto(mercadoCidade, chocolate, 5.30).
produto(mercadoCidade, leite_condensado, 4.30).
produto(mercadoCidade, chocolate_po, 3.60).
produto(mercadoCidade, granulado, 2.60).
produto(mercadoCidade, massa_folhada, 6.30).
produto(mercadoCidade, alho_poro, 3.60).
produto(mercadoCidade, creme_leite, 3.30).
produto(mercadoCidade, carne_moida, 22.30).
produto(mercadoCidade, frango_desfiado, 14.30).
produto(mercadoCidade, milho, 2.30).
produto(mercadoCidade, ervilha, 2.10).
produto(mercadoCidade, caldo_galinha, 1.60).
produto(mercadoCidade, farinha_trigo, 3.10).
produto(mercadoCidade, farofa, 4.10).
produto(mercadoCidade, coco_ralado, 3.60).
produto(mercadoCidade, acucar, 2.10).
produto(mercadoCidade, salsa, 1.90).
produto(mercadoCidade, maracuja, 6.30).
produto(mercadoCidade, gelatina, 2.60).
produto(mercadoCidade, mandioca, 2.60).
produto(mercadoCidade, queijo_parmesao, 10.30).
produto(mercadoCidade, arroz_arboreo, 6.30).
produto(mercadoCidade, cogumelos, 12.30).
produto(mercadoCidade, caldo_legumes, 2.60).
produto(mercadoCidade, massa_lasanha, 7.30).
produto(mercadoCidade, presunto, 6.30).
produto(mercadoCidade, palmito, 5.30).
produto(mercadoCidade, sardinha, 4.30).
produto(mercadoCidade, pao, 2.60).
produto(mercadoCidade, leite_de_coco, 3.30).
produto(mercadoCidade, azeite_de_dende, 5.60).
produto(mercadoCidade, camarão, 18.30).
produto(mercadoCidade, amendoim, 7.30).

produto(mercadoEstrela, arroz, 4.60).
produto(mercadoEstrela, feijao, 3.60).
produto(mercadoEstrela, leite, 3.30).
produto(mercadoEstrela, carne, 24.80).
produto(mercadoEstrela, pao, 5.90).
produto(mercadoEstrela, laranja, 3.80).
produto(mercadoEstrela, ovos, 7.20).
produto(mercadoEstrela, macarrao, 3.40).
produto(mercadoEstrela, queijo, 8.40).
produto(mercadoEstrela, manteiga, 4.70).
produto(mercadoEstrela, acucar, 3.50).
produto(mercadoEstrela, tomate, 4.10).
produto(mercadoEstrela, alface, 3.40).
produto(mercadoEstrela, cenoura, 2.90).
produto(mercadoEstrela, batata, 4.20).
produto(mercadoEstrela, cafe, 7.20).
produto(mercadoEstrela, oleo, 5.70).
produto(mercadoEstrela, cebola, 2.60).
produto(mercadoEstrela, sal, 1.10).
produto(mercadoEstrela, alho, 2.40).
produto(mercadoEstrela, pimentao, 2.90).
produto(mercadoEstrela, peixe, 18.00).
produto(mercadoEstrela, frango, 12.00).
produto(mercadoEstrela, linguiça, 9.00).
produto(mercadoEstrela, polvilho_doce, 7.00).
produto(mercadoEstrela, queijo_minas, 15.00).
produto(mercadoEstrela, farinha, 4.50).
produto(mercadoEstrela, chocolate, 5.00).
produto(mercadoEstrela, leite_condensado, 4.00).
produto(mercadoEstrela, chocolate_po, 3.50).
produto(mercadoEstrela, granulado, 2.50).
produto(mercadoEstrela, massa_folhada, 6.00).
produto(mercadoEstrela, alho_poro, 3.50).
produto(mercadoEstrela, creme_leite, 3.00).
produto(mercadoEstrela, carne_moida, 22.00).
produto(mercadoEstrela, frango_desfiado, 14.00).
produto(mercadoEstrela, milho, 2.20).
produto(mercadoEstrela, ervilha, 2.00).
produto(mercadoEstrela, caldo_galinha, 1.50).
produto(mercadoEstrela, farinha_trigo, 3.00).
produto(mercadoEstrela, farofa, 4.00).
produto(mercadoEstrela, coco_ralado, 3.50).
produto(mercadoEstrela, acucar, 2.00).
produto(mercadoEstrela, salsa, 1.80).
produto(mercadoEstrela, maracuja, 6.00).
produto(mercadoEstrela, gelatina, 2.50).
produto(mercadoEstrela, mandioca, 2.50).
produto(mercadoEstrela, queijo_parmesao, 10.00).
produto(mercadoEstrela, arroz_arboreo, 6.00).
produto(mercadoEstrela, cogumelos, 12.00).
produto(mercadoEstrela, caldo_legumes, 2.50).
produto(mercadoEstrela, massa_lasanha, 7.00).
produto(mercadoEstrela, presunto, 6.00).
produto(mercadoEstrela, palmito, 5.00).
produto(mercadoEstrela, sardinha, 4.00).
produto(mercadoEstrela, pao, 2.50).
produto(mercadoEstrela, leite_de_coco, 3.00).
produto(mercadoEstrela, azeite_de_dende, 5.50).
produto(mercadoEstrela, camarão, 18.00).
produto(mercadoEstrela, amendoim, 7.00).

produto(mercadoSantaLuzia, arroz, 4.40).
produto(mercadoSantaLuzia, feijao, 3.40).
produto(mercadoSantaLuzia, leite, 3.20).
produto(mercadoSantaLuzia, carne, 24.30).
produto(mercadoSantaLuzia, pao, 5.60).
produto(mercadoSantaLuzia, abobora, 6.00).
produto(mercadoSantaLuzia, cafe, 7.30).
produto(mercadoSantaLuzia, manteiga, 4.90).
produto(mercadoSantaLuzia, queijo, 8.50).
produto(mercadoSantaLuzia, ovos, 7.30).
produto(mercadoSantaLuzia, tomate, 4.30).
produto(mercadoSantaLuzia, macarrao, 3.50).
produto(mercadoSantaLuzia, laranja, 3.90).
produto(mercadoSantaLuzia, alface, 3.50).
produto(mercadoSantaLuzia, cenoura, 2.80).
produto(mercadoSantaLuzia, batata, 4.00).
produto(mercadoSantaLuzia, oleo, 5.80).
produto(mercadoSantaLuzia, cebola, 2.70).
produto(mercadoSantaLuzia, sal, 1.10).
produto(mercadoSantaLuzia, alho, 2.40).
produto(mercadoSantaLuzia, pimentao, 2.90).
produto(mercadoSantaLuzia, peixe, 17.90).
produto(mercadoSantaLuzia, frango, 11.90).
produto(mercadoSantaLuzia, linguiça, 8.90).
produto(mercadoSantaLuzia, polvilho_doce, 6.90).
produto(mercadoSantaLuzia, queijo_minas, 14.90).
produto(mercadoSantaLuzia, farinha, 4.50).
produto(mercadoSantaLuzia, chocolate, 4.80).
produto(mercadoSantaLuzia, leite_condensado, 3.80).
produto(mercadoSantaLuzia, chocolate_po, 3.40).
produto(mercadoSantaLuzia, granulado, 2.40).
produto(mercadoSantaLuzia, massa_folhada, 5.80).
produto(mercadoSantaLuzia, alho_poro, 3.40).
produto(mercadoSantaLuzia, creme_leite, 2.80).
produto(mercadoSantaLuzia, carne_moida, 21.80).
produto(mercadoSantaLuzia, frango_desfiado, 13.80).
produto(mercadoSantaLuzia, milho, 2.20).
produto(mercadoSantaLuzia, ervilha, 2.00).
produto(mercadoSantaLuzia, caldo_galinha, 1.50).
produto(mercadoSantaLuzia, farinha_trigo, 3.00).
produto(mercadoSantaLuzia, farofa, 3.90).
produto(mercadoSantaLuzia, coco_ralado, 3.40).
produto(mercadoSantaLuzia, acucar, 1.90).
produto(mercadoSantaLuzia, salsa, 1.70).
produto(mercadoSantaLuzia, maracuja, 5.80).
produto(mercadoSantaLuzia, gelatina, 2.40).
produto(mercadoSantaLuzia, mandioca, 2.40).
produto(mercadoSantaLuzia, queijo_parmesao, 9.80).
produto(mercadoSantaLuzia, arroz_arboreo, 5.80).
produto(mercadoSantaLuzia, cogumelos, 11.80).
produto(mercadoSantaLuzia, caldo_legumes, 2.40).
produto(mercadoSantaLuzia, massa_lasanha, 6.80).
produto(mercadoSantaLuzia, presunto, 5.80).
produto(mercadoSantaLuzia, palmito, 4.80).
produto(mercadoSantaLuzia, sardinha, 3.80).
produto(mercadoSantaLuzia, pao, 2.40).
produto(mercadoSantaLuzia, leite_de_coco, 2.80).
produto(mercadoSantaLuzia, azeite_de_dende, 5.40).
produto(mercadoSantaLuzia, camarão, 17.90).
produto(mercadoSantaLuzia, amendoim, 6.90).

produto(mercadoSuperMais, arroz, 4.50).
produto(mercadoSuperMais, feijao, 4.00).
produto(mercadoSuperMais, leite, 3.50).
produto(mercadoSuperMais, cafe, 7.20).
produto(mercadoSuperMais, manteiga, 4.80).
produto(mercadoSuperMais, ovos, 6.80).
produto(mercadoSuperMais, macarrao, 3.60).
produto(mercadoSuperMais, queijo, 8.30).
produto(mercadoSuperMais, carne, 25.30).
produto(mercadoSuperMais, pao, 6.20).
produto(mercadoSuperMais, tomate, 4.20).
produto(mercadoSuperMais, laranja, 4.10).
produto(mercadoSuperMais, abacaxi, 5.60).
produto(mercadoSuperMais, abobora, 5.70).
produto(mercadoSuperMais, alface, 3.40).
produto(mercadoSuperMais, cenoura, 2.90).
produto(mercadoSuperMais, batata, 4.20).
produto(mercadoSuperMais, oleo, 6.10).
produto(mercadoSuperMais, cebola, 2.90).
produto(mercadoSuperMais, sal, 1.30).
produto(mercadoSuperMais, alho, 2.60).
produto(mercadoSuperMais, pimentao, 3.10).
produto(mercadoSuperMais, peixe, 18.20).
produto(mercadoSuperMais, frango, 12.20).
produto(mercadoSuperMais, linguiça, 9.20).
produto(mercadoSuperMais, polvilho_doce, 7.20).
produto(mercadoSuperMais, queijo_minas, 15.20).
produto(mercadoSuperMais, farinha, 4.70).
produto(mercadoSuperMais, chocolate, 5.20).
produto(mercadoSuperMais, leite_condensado, 4.20).
produto(mercadoSuperMais, chocolate_po, 3.60).
produto(mercadoSuperMais, granulado, 2.60).
produto(mercadoSuperMais, massa_folhada, 6.20).
produto(mercadoSuperMais, alho_poro, 3.60).
produto(mercadoSuperMais, creme_leite, 3.20).
produto(mercadoSuperMais, carne_moida, 22.20).
produto(mercadoSuperMais, frango_desfiado, 14.20).
produto(mercadoSuperMais, milho, 2.30).
produto(mercadoSuperMais, ervilha, 2.10).
produto(mercadoSuperMais, caldo_galinha, 1.60).
produto(mercadoSuperMais, farinha_trigo, 3.10).
produto(mercadoSuperMais, farofa, 4.20).
produto(mercadoSuperMais, coco_ralado, 3.60).
produto(mercadoSuperMais, acucar, 2.10).
produto(mercadoSuperMais, salsa, 1.90).
produto(mercadoSuperMais, maracuja, 6.20).
produto(mercadoSuperMais, gelatina, 2.60).
produto(mercadoSuperMais, mandioca, 2.60).
produto(mercadoSuperMais, queijo_parmesao, 10.20).
produto(mercadoSuperMais, arroz_arboreo, 6.20).
produto(mercadoSuperMais, cogumelos, 12.20).
produto(mercadoSuperMais, caldo_legumes, 2.60).
produto(mercadoSuperMais, massa_lasanha, 7.20).
produto(mercadoSuperMais, presunto, 6.20).
produto(mercadoSuperMais, palmito, 5.20).
produto(mercadoSuperMais, sardinha, 4.20).
produto(mercadoSuperMais, pao, 2.60).
produto(mercadoSuperMais, leite_de_coco, 3.20).
produto(mercadoSuperMais, azeite_de_dende, 5.60).
produto(mercadoSuperMais, camarão, 18.20).
produto(mercadoSuperMais, amendoim, 7.20).

produto(mercadoFamilia, arroz, 4.30).
produto(mercadoFamilia, feijao, 3.20).
produto(mercadoFamilia, leite, 3.00).
produto(mercadoFamilia, carne, 25.50).
produto(mercadoFamilia, pao, 6.10).
produto(mercadoFamilia, ovos, 6.80).
produto(mercadoFamilia, tomate, 4.20).
produto(mercadoFamilia, acucar, 3.50).
produto(mercadoFamilia, cafe, 7.00).
produto(mercadoFamilia, manteiga, 4.60).
produto(mercadoFamilia, macarrao, 3.50).
produto(mercadoFamilia, laranja, 4.00).
produto(mercadoFamilia, abobora, 5.70).
produto(mercadoFamilia, alface, 3.20).
produto(mercadoFamilia, cenoura, 2.80).
produto(mercadoFamilia, batata, 4.00).
produto(mercadoFamilia, queijo, 8.20).
produto(mercadoFamilia, oleo, 5.80).
produto(mercadoFamilia, cebola, 2.70).
produto(mercadoFamilia, sal, 1.10).
produto(mercadoFamilia, alho, 2.40).
produto(mercadoFamilia, pimentao, 2.90).
produto(mercadoFamilia, peixe, 18.10).
produto(mercadoFamilia, frango, 12.10).
produto(mercadoFamilia, linguiça, 9.10).
produto(mercadoFamilia, polvilho_doce, 7.10).
produto(mercadoFamilia, queijo_minas, 15.10).
produto(mercadoFamilia, farinha, 4.60).
produto(mercadoFamilia, chocolate, 5.10).
produto(mercadoFamilia, leite_condensado, 4.10).
produto(mercadoFamilia, chocolate_po, 3.50).
produto(mercadoFamilia, granulado, 2.50).
produto(mercadoFamilia, massa_folhada, 6.10).
produto(mercadoFamilia, alho_poro, 3.50).
produto(mercadoFamilia, creme_leite, 3.10).
produto(mercadoFamilia, carne_moida, 22.10).
produto(mercadoFamilia, frango_desfiado, 14.10).
produto(mercadoFamilia, milho, 2.20).
produto(mercadoFamilia, ervilha, 2.00).
produto(mercadoFamilia, caldo_galinha, 1.50).
produto(mercadoFamilia, farinha_trigo, 3.00).
produto(mercadoFamilia, farofa, 4.00).
produto(mercadoFamilia, coco_ralado, 3.50).
produto(mercadoFamilia, acucar, 2.00).
produto(mercadoFamilia, salsa, 1.80).
produto(mercadoFamilia, maracuja, 6.00).
produto(mercadoFamilia, gelatina, 2.50).
produto(mercadoFamilia, mandioca, 2.50).
produto(mercadoFamilia, queijo_parmesao, 10.00).
produto(mercadoFamilia, arroz_arboreo, 6.00).
produto(mercadoFamilia, cogumelos, 12.00).
produto(mercadoFamilia, caldo_legumes, 2.50).
produto(mercadoFamilia, massa_lasanha, 7.00).
produto(mercadoFamilia, presunto, 6.00).
produto(mercadoFamilia, palmito, 5.00).
produto(mercadoFamilia, sardinha, 4.00).
produto(mercadoFamilia, pao, 2.50).
produto(mercadoFamilia, leite_de_coco, 3.00).
produto(mercadoFamilia, azeite_de_dende, 5.50).
produto(mercadoFamilia, camarão, 18.00).
produto(mercadoFamilia, amendoim, 7.00).

produto(mercadoAlvorada, arroz, 4.10).
produto(mercadoAlvorada, feijao, 3.50).
produto(mercadoAlvorada, leite, 3.20).
produto(mercadoAlvorada, carne, 24.70).
produto(mercadoAlvorada, pao, 5.90).
produto(mercadoAlvorada, queijo, 8.20).
produto(mercadoAlvorada, manteiga, 4.60).
produto(mercadoAlvorada, abobora, 5.70).
produto(mercadoAlvorada, ovos, 7.00).
produto(mercadoAlvorada, cafe, 7.30).
produto(mercadoAlvorada, acucar, 3.60).
produto(mercadoAlvorada, macarrao, 3.50).
produto(mercadoAlvorada, laranja, 4.00).
produto(mercadoAlvorada, alface, 3.30).
produto(mercadoAlvorada, cenoura, 2.80).
produto(mercadoAlvorada, batata, 4.10).
produto(mercadoAlvorada, tomate, 4.20).
produto(mercadoAlvorada, oleo, 5.90).
produto(mercadoAlvorada, cebola, 2.80).
produto(mercadoAlvorada, sal, 1.20).
produto(mercadoAlvorada, alho, 2.50).
produto(mercadoAlvorada, pimentao, 3.00).
produto(mercadoAlvorada, peixe, 18.10).
produto(mercadoAlvorada, frango, 12.10).
produto(mercadoAlvorada, linguiça, 9.10).
produto(mercadoAlvorada, polvilho_doce, 7.10).
produto(mercadoAlvorada, queijo_minas, 15.10).
produto(mercadoAlvorada, farinha, 4.60).
produto(mercadoAlvorada, chocolate, 5.10).
produto(mercadoAlvorada, leite_condensado, 4.10).
produto(mercadoAlvorada, chocolate_po, 3.50).
produto(mercadoAlvorada, granulado, 2.50).
produto(mercadoAlvorada, massa_folhada, 6.10).
produto(mercadoAlvorada, alho_poro, 3.50).
produto(mercadoAlvorada, creme_leite, 3.10).
produto(mercadoAlvorada, carne_moida, 22.10).
produto(mercadoAlvorada, frango_desfiado, 14.10).
produto(mercadoAlvorada, milho, 2.20).
produto(mercadoAlvorada, ervilha, 2.00).
produto(mercadoAlvorada, caldo_galinha, 1.50).
produto(mercadoAlvorada, farinha_trigo, 3.00).
produto(mercadoAlvorada, farofa, 4.00).
produto(mercadoAlvorada, coco_ralado, 3.50).
produto(mercadoAlvorada, acucar, 2.00).
produto(mercadoAlvorada, salsa, 1.80).
produto(mercadoAlvorada, maracuja, 6.00).
produto(mercadoAlvorada, gelatina, 2.50).
produto(mercadoAlvorada, mandioca, 2.50).
produto(mercadoAlvorada, queijo_parmesao, 10.00).
produto(mercadoAlvorada, arroz_arboreo, 6.00).
produto(mercadoAlvorada, cogumelos, 12.00).
produto(mercadoAlvorada, caldo_legumes, 2.50).
produto(mercadoAlvorada, massa_lasanha, 7.00).
produto(mercadoAlvorada, presunto, 6.00).
produto(mercadoAlvorada, palmito, 5.00).
produto(mercadoAlvorada, sardinha, 4.00).
produto(mercadoAlvorada, pao, 2.50).
produto(mercadoAlvorada, leite_de_coco, 3.00).
produto(mercadoAlvorada, azeite_de_dende, 5.50).
produto(mercadoAlvorada, camarão, 18.00).
produto(mercadoAlvorada, amendoim, 7.00).

produto(mercadoPrata, arroz, 4.60).
produto(mercadoPrata, feijao, 3.80).
produto(mercadoPrata, leite, 3.10).
produto(mercadoPrata, carne, 25.00).
produto(mercadoPrata, pao, 6.50).
produto(mercadoPrata, macarrao, 3.30).
produto(mercadoPrata, cafe, 7.00).
produto(mercadoPrata, ovos, 7.10).
produto(mercadoPrata, queijo, 8.20).
produto(mercadoPrata, manteiga, 4.60).
produto(mercadoPrata, abobora, 5.60).
produto(mercadoPrata, tomate, 4.10).
produto(mercadoPrata, acucar, 3.50).
produto(mercadoPrata, laranja, 3.80).
produto(mercadoPrata, alface, 3.20).
produto(mercadoPrata, cenoura, 2.70).
produto(mercadoPrata, batata, 4.00).
produto(mercadoPrata, oleo, 5.80).
produto(mercadoPrata, cebola, 2.70).
produto(mercadoPrata, sal, 1.10).
produto(mercadoPrata, alho, 2.40).
produto(mercadoPrata, pimentao, 2.90).
produto(mercadoPrata, peixe, 18.00).
produto(mercadoPrata, frango, 12.00).
produto(mercadoPrata, linguiça, 9.00).
produto(mercadoPrata, polvilho_doce, 7.00).
produto(mercadoPrata, queijo_minas, 15.00).
produto(mercadoPrata, farinha, 4.50).
produto(mercadoPrata, chocolate, 5.00).
produto(mercadoPrata, leite_condensado, 4.00).
produto(mercadoPrata, chocolate_po, 3.50).
produto(mercadoPrata, granulado, 2.50).
produto(mercadoPrata, massa_folhada, 6.00).
produto(mercadoPrata, alho_poro, 3.50).
produto(mercadoPrata, creme_leite, 3.00).
produto(mercadoPrata, carne_moida, 22.00).
produto(mercadoPrata, frango_desfiado, 14.00).
produto(mercadoPrata, milho, 2.20).
produto(mercadoPrata, ervilha, 2.00).
produto(mercadoPrata, caldo_galinha, 1.50).
produto(mercadoPrata, farinha_trigo, 3.00).
produto(mercadoPrata, farofa, 4.00).
produto(mercadoPrata, coco_ralado, 3.50).
produto(mercadoPrata, acucar, 2.00).
produto(mercadoPrata, salsa, 1.80).
produto(mercadoPrata, maracuja, 6.00).
produto(mercadoPrata, gelatina, 2.50).
produto(mercadoPrata, mandioca, 2.50).
produto(mercadoPrata, queijo_parmesao, 10.00).
produto(mercadoPrata, arroz_arboreo, 6.00).
produto(mercadoPrata, cogumelos, 12.00).
produto(mercadoPrata, caldo_legumes, 2.50).
produto(mercadoPrata, massa_lasanha, 7.00).
produto(mercadoPrata, presunto, 6.00).
produto(mercadoPrata, palmito, 5.00).
produto(mercadoPrata, sardinha, 4.00).
produto(mercadoPrata, pao, 2.50).
produto(mercadoPrata, leite_de_coco, 3.00).
produto(mercadoPrata, azeite_de_dende, 5.50).
produto(mercadoPrata, camarão, 18.00).
produto(mercadoPrata, amendoim, 7.00).

produto(mercadoVitoria, arroz, 4.20).
produto(mercadoVitoria, feijao, 3.60).
produto(mercadoVitoria, leite, 3.30).
produto(mercadoVitoria, carne, 24.90).
produto(mercadoVitoria, pao, 6.00).
produto(mercadoVitoria, tomate, 4.20).
produto(mercadoVitoria, laranja, 3.90).
produto(mercadoVitoria, queijo, 8.40).
produto(mercadoVitoria, ovos, 7.20).
produto(mercadoVitoria, manteiga, 4.70).
produto(mercadoVitoria, abobora, 5.80).
produto(mercadoVitoria, cafe, 7.10).
produto(mercadoVitoria, acucar, 3.60).
produto(mercadoVitoria, alface, 3.20).
produto(mercadoVitoria, cenoura, 2.80).
produto(mercadoVitoria, batata, 4.00).
produto(mercadoVitoria, macarrao, 3.40).
produto(mercadoVitoria, oleo, 5.90).
produto(mercadoVitoria, cebola, 2.80).
produto(mercadoVitoria, sal, 1.20).
produto(mercadoVitoria, alho, 2.50).
produto(mercadoVitoria, pimentao, 3.00).
produto(mercadoVitoria, peixe, 18.10).
produto(mercadoVitoria, frango, 12.10).
produto(mercadoVitoria, linguiça, 9.10).
produto(mercadoVitoria, polvilho_doce, 7.10).
produto(mercadoVitoria, queijo_minas, 15.10).
produto(mercadoVitoria, farinha, 4.60).
produto(mercadoVitoria, chocolate, 5.10).
produto(mercadoVitoria, leite_condensado, 4.10).
produto(mercadoVitoria, chocolate_po, 3.50).
produto(mercadoVitoria, granulado, 2.50).
produto(mercadoVitoria, massa_folhada, 6.10).
produto(mercadoVitoria, alho_poro, 3.50).
produto(mercadoVitoria, creme_leite, 3.10).
produto(mercadoVitoria, carne_moida, 22.10).
produto(mercadoVitoria, frango_desfiado, 14.10).
produto(mercadoVitoria, milho, 2.20).
produto(mercadoVitoria, ervilha, 2.00).
produto(mercadoVitoria, caldo_galinha, 1.50).
produto(mercadoVitoria, farinha_trigo, 3.00).
produto(mercadoVitoria, farofa, 4.00).
produto(mercadoVitoria, coco_ralado, 3.50).
produto(mercadoVitoria, acucar, 2.00).
produto(mercadoVitoria, salsa, 1.80).
produto(mercadoVitoria, maracuja, 6.00).
produto(mercadoVitoria, gelatina, 2.50).
produto(mercadoVitoria, mandioca, 2.50).
produto(mercadoVitoria, queijo_parmesao, 10.00).
produto(mercadoVitoria, arroz_arboreo, 6.00).
produto(mercadoVitoria, cogumelos, 12.00).
produto(mercadoVitoria, caldo_legumes, 2.50).
produto(mercadoVitoria, massa_lasanha, 7.00).
produto(mercadoVitoria, presunto, 6.00).
produto(mercadoVitoria, palmito, 5.00).
produto(mercadoVitoria, sardinha, 4.00).
produto(mercadoVitoria, pao, 2.50).
produto(mercadoVitoria, leite_de_coco, 3.00).
produto(mercadoVitoria, azeite_de_dende, 5.50).
produto(mercadoVitoria, camarão, 18.00).
produto(mercadoVitoria, amendoim, 7.00).

produto(mercadoPremium, arroz, 4.50).
produto(mercadoPremium, feijao, 4.30).
produto(mercadoPremium, leite, 3.20).
produto(mercadoPremium, carne, 26.00).
produto(mercadoPremium, pao, 6.70).
produto(mercadoPremium, abacaxi, 5.50).
produto(mercadoPremium, acucar, 3.60).
produto(mercadoPremium, manteiga, 4.80).
produto(mercadoPremium, queijo, 8.50).
produto(mercadoPremium, ovos, 7.40).
produto(mercadoPremium, cafe, 7.30).
produto(mercadoPremium, macarrao, 3.50).
produto(mercadoPremium, laranja, 4.00).
produto(mercadoPremium, alface, 3.30).
produto(mercadoPremium, cenoura, 2.90).
produto(mercadoPremium, batata, 4.20).
produto(mercadoPremium, abobora, 5.70).
produto(mercadoPremium, oleo, 5.90).
produto(mercadoPremium, cebola, 2.80).
produto(mercadoPremium, sal, 1.20).
produto(mercadoPremium, alho, 2.50).
produto(mercadoPremium, pimentao, 3.00).
produto(mercadoPremium, peixe, 18.30).
produto(mercadoPremium, frango, 12.30).
produto(mercadoPremium, linguiça, 9.30).
produto(mercadoPremium, polvilho_doce, 7.30).
produto(mercadoPremium, queijo_minas, 15.30).
produto(mercadoPremium, farinha, 4.80).
produto(mercadoPremium, chocolate, 5.30).
produto(mercadoPremium, leite_condensado, 4.30).
produto(mercadoPremium, chocolate_po, 3.60).
produto(mercadoPremium, granulado, 2.60).
produto(mercadoPremium, massa_folhada, 6.30).
produto(mercadoPremium, alho_poro, 3.60).
produto(mercadoPremium, creme_leite, 3.30).
produto(mercadoPremium, carne_moida, 22.30).
produto(mercadoPremium, frango_desfiado, 14.30).
produto(mercadoPremium, milho, 2.30).
produto(mercadoPremium, ervilha, 2.10).
produto(mercadoPremium, caldo_galinha, 1.60).
produto(mercadoPremium, farinha_trigo, 3.10).
produto(mercadoPremium, farofa, 4.10).
produto(mercadoPremium, coco_ralado, 3.60).
produto(mercadoPremium, acucar, 2.10).
produto(mercadoPremium, salsa, 1.90).
produto(mercadoPremium, maracuja, 6.30).
produto(mercadoPremium, gelatina, 2.60).
produto(mercadoPremium, mandioca, 2.60).
produto(mercadoPremium, queijo_parmesao, 10.30).
produto(mercadoPremium, arroz_arboreo, 6.30).
produto(mercadoPremium, cogumelos, 12.30).
produto(mercadoPremium, caldo_legumes, 2.60).
produto(mercadoPremium, massa_lasanha, 7.30).
produto(mercadoPremium, presunto, 6.30).
produto(mercadoPremium, palmito, 5.30).
produto(mercadoPremium, sardinha, 4.30).
produto(mercadoPremium, pao, 2.60).
produto(mercadoPremium, leite_de_coco, 3.30).
produto(mercadoPremium, azeite_de_dende, 5.60).
produto(mercadoPremium, camarão, 18.30).
produto(mercadoPremium, amendoim, 7.30).

produto(mercadoElite, arroz, 4.70).
produto(mercadoElite, feijao, 4.00).
produto(mercadoElite, leite, 3.50).
produto(mercadoElite, cafe, 7.50).
produto(mercadoElite, manteiga, 5.00).
produto(mercadoElite, queijo, 8.50).
produto(mercadoElite, ovos, 7.30).
produto(mercadoElite, tomate, 4.30).
produto(mercadoElite, carne, 25.30).
produto(mercadoElite, pao, 6.20).
produto(mercadoElite, abacaxi, 5.60).
produto(mercadoElite, laranja, 4.10).
produto(mercadoElite, abobora, 5.90).
produto(mercadoElite, acucar, 3.60).
produto(mercadoElite, alface, 3.40).
produto(mercadoElite, cenoura, 2.80).
produto(mercadoElite, batata, 4.20).
produto(mercadoElite, macarrao, 3.40).
produto(mercadoElite, oleo, 6.10).
produto(mercadoElite, cebola, 2.90).
produto(mercadoElite, sal, 1.30).
produto(mercadoElite, alho, 2.60).
produto(mercadoElite, pimentao, 3.10).
produto(mercadoElite, peixe, 18.40).
produto(mercadoElite, frango, 12.40).
produto(mercadoElite, linguiça, 9.40).
produto(mercadoElite, polvilho_doce, 7.40).
produto(mercadoElite, queijo_minas, 15.40).
produto(mercadoElite, farinha, 4.80).
produto(mercadoElite, chocolate, 5.40).
produto(mercadoElite, leite_condensado, 4.40).
produto(mercadoElite, chocolate_po, 3.70).
produto(mercadoElite, granulado, 2.70).
produto(mercadoElite, massa_folhada, 6.40).
produto(mercadoElite, alho_poro, 3.70).
produto(mercadoElite, creme_leite, 3.40).
produto(mercadoElite, carne_moida, 22.40).
produto(mercadoElite, frango_desfiado, 14.40).
produto(mercadoElite, milho, 2.40).
produto(mercadoElite, ervilha, 2.20).
produto(mercadoElite, caldo_galinha, 1.70).
produto(mercadoElite, farinha_trigo, 3.20).
produto(mercadoElite, farofa, 4.20).
produto(mercadoElite, coco_ralado, 3.70).
produto(mercadoElite, acucar, 2.20).
produto(mercadoElite, salsa, 2.00).
produto(mercadoElite, maracuja, 6.40).
produto(mercadoElite, gelatina, 2.70).
produto(mercadoElite, mandioca, 2.70).
produto(mercadoElite, queijo_parmesao, 10.40).
produto(mercadoElite, arroz_arboreo, 6.40).
produto(mercadoElite, cogumelos, 12.40).
produto(mercadoElite, caldo_legumes, 2.70).
produto(mercadoElite, massa_lasanha, 7.40).
produto(mercadoElite, presunto, 6.40).
produto(mercadoElite, palmito, 5.40).
produto(mercadoElite, sardinha, 4.40).
produto(mercadoElite, pao, 2.70).
produto(mercadoElite, leite_de_coco, 3.40).
produto(mercadoElite, azeite_de_dende, 5.70).
produto(mercadoElite, camarão, 18.40).
produto(mercadoElite, amendoim, 7.40).

produto(mercadoDestaque, arroz, 4.40).
produto(mercadoDestaque, feijao, 3.50).
produto(mercadoDestaque, leite, 3.10).
produto(mercadoDestaque, carne, 25.50).
produto(mercadoDestaque, pao, 6.20).
produto(mercadoDestaque, laranja, 4.00).
produto(mercadoDestaque, acucar, 3.70).
produto(mercadoDestaque, cafe, 7.20).
produto(mercadoDestaque, abobora, 5.80).
produto(mercadoDestaque, queijo, 8.20).
produto(mercadoDestaque, ovos, 7.00).
produto(mercadoDestaque, macarrao, 3.40).
produto(mercadoDestaque, tomate, 4.20).
produto(mercadoDestaque, manteiga, 4.60).
produto(mercadoDestaque, alface, 3.30).
produto(mercadoDestaque, cenoura, 2.90).
produto(mercadoDestaque, batata, 4.10).
produto(mercadoDestaque, oleo, 5.90).
produto(mercadoDestaque, cebola, 2.80).
produto(mercadoDestaque, sal, 1.20).
produto(mercadoDestaque, alho, 2.50).
produto(mercadoDestaque, pimentao, 3.00).
produto(mercadoDestaque, peixe, 18.30).
produto(mercadoDestaque, frango, 12.30).
produto(mercadoDestaque, linguiça, 9.30).
produto(mercadoDestaque, polvilho_doce, 7.30).
produto(mercadoDestaque, queijo_minas, 15.30).
produto(mercadoDestaque, farinha, 4.80).
produto(mercadoDestaque, chocolate, 5.30).
produto(mercadoDestaque, leite_condensado, 4.30).
produto(mercadoDestaque, chocolate_po, 3.60).
produto(mercadoDestaque, granulado, 2.60).
produto(mercadoDestaque, massa_folhada, 6.30).
produto(mercadoDestaque, alho_poro, 3.60).
produto(mercadoDestaque, creme_leite, 3.30).
produto(mercadoDestaque, carne_moida, 22.30).
produto(mercadoDestaque, frango_desfiado, 14.30).
produto(mercadoDestaque, milho, 2.30).
produto(mercadoDestaque, ervilha, 2.10).
produto(mercadoDestaque, caldo_galinha, 1.60).
produto(mercadoDestaque, farinha_trigo, 3.10).
produto(mercadoDestaque, farofa, 4.10).
produto(mercadoDestaque, coco_ralado, 3.60).
produto(mercadoDestaque, acucar, 2.10).
produto(mercadoDestaque, salsa, 1.90).
produto(mercadoDestaque, maracuja, 6.30).
produto(mercadoDestaque, gelatina, 2.60).
produto(mercadoDestaque, mandioca, 2.60).
produto(mercadoDestaque, queijo_parmesao, 10.30).
produto(mercadoDestaque, arroz_arboreo, 6.30).
produto(mercadoDestaque, cogumelos, 12.30).
produto(mercadoDestaque, caldo_legumes, 2.60).
produto(mercadoDestaque, massa_lasanha, 7.30).
produto(mercadoDestaque, presunto, 6.30).
produto(mercadoDestaque, palmito, 5.30).
produto(mercadoDestaque, sardinha, 4.30).
produto(mercadoDestaque, pao, 2.60).
produto(mercadoDestaque, leite_de_coco, 3.30).
produto(mercadoDestaque, azeite_de_dende, 5.60).
produto(mercadoDestaque, camarão, 18.30).
produto(mercadoDestaque, amendoim, 7.30).

produto(mercadoReal, arroz, 4.50).
produto(mercadoReal, feijao, 3.70).
produto(mercadoReal, leite, 3.20).
produto(mercadoReal, carne, 24.90).
produto(mercadoReal, pao, 6.10).
produto(mercadoReal, abobora, 5.80).
produto(mercadoReal, macarrao, 3.40).
produto(mercadoReal, queijo, 8.00).
produto(mercadoReal, manteiga, 4.50).
produto(mercadoReal, cafe, 7.10).
produto(mercadoReal, tomate, 4.10).
produto(mercadoReal, laranja, 3.80).
produto(mercadoReal, alface, 3.20).
produto(mercadoReal, cenoura, 2.70).
produto(mercadoReal, batata, 4.00).
produto(mercadoReal, ovos, 7.00).
produto(mercadoReal, acucar, 3.60).
produto(mercadoReal, oleo, 5.80).
produto(mercadoReal, cebola, 2.70).
produto(mercadoReal, sal, 1.10).
produto(mercadoReal, alho, 2.40).
produto(mercadoReal, pimentao, 2.90).
produto(mercadoReal, peixe, 18.00).
produto(mercadoReal, frango, 12.00).
produto(mercadoReal, linguiça, 9.00).
produto(mercadoReal, polvilho_doce, 7.00).
produto(mercadoReal, queijo_minas, 15.00).
produto(mercadoReal, farinha, 4.50).
produto(mercadoReal, chocolate, 5.00).
produto(mercadoReal, leite_condensado, 4.00).
produto(mercadoReal, chocolate_po, 3.50).
produto(mercadoReal, granulado, 2.50).
produto(mercadoReal, massa_folhada, 6.00).
produto(mercadoReal, alho_poro, 3.50).
produto(mercadoReal, creme_leite, 3.00).
produto(mercadoReal, carne_moida, 22.00).
produto(mercadoReal, frango_desfiado, 14.00).
produto(mercadoReal, milho, 2.20).
produto(mercadoReal, ervilha, 2.00).
produto(mercadoReal, caldo_galinha, 1.50).
produto(mercadoReal, farinha_trigo, 3.00).
produto(mercadoReal, farofa, 4.00).
produto(mercadoReal, coco_ralado, 3.50).
produto(mercadoReal, acucar, 2.00).
produto(mercadoReal, salsa, 1.80).
produto(mercadoReal, maracuja, 6.00).
produto(mercadoReal, gelatina, 2.50).
produto(mercadoReal, mandioca, 2.50).
produto(mercadoReal, queijo_parmesao, 10.00).
produto(mercadoReal, arroz_arboreo, 6.00).
produto(mercadoReal, cogumelos, 12.00).
produto(mercadoReal, caldo_legumes, 2.50).
produto(mercadoReal, massa_lasanha, 7.00).
produto(mercadoReal, presunto, 6.00).
produto(mercadoReal, palmito, 5.00).
produto(mercadoReal, sardinha, 4.00).
produto(mercadoReal, pao, 2.50).
produto(mercadoReal, leite_de_coco, 3.00).
produto(mercadoReal, azeite_de_dende, 5.50).
produto(mercadoReal, camarão, 18.00).
produto(mercadoReal, amendoim, 7.00).

produto(mercadoCompreBem, arroz, 4.30).
produto(mercadoCompreBem, feijao, 3.40).
produto(mercadoCompreBem, leite, 3.00).
produto(mercadoCompreBem, carne, 25.30).
produto(mercadoCompreBem, pao, 5.90).
produto(mercadoCompreBem, macarrao, 3.50).
produto(mercadoCompreBem, ovos, 6.90).
produto(mercadoCompreBem, tomate, 4.10).
produto(mercadoCompreBem, abobora, 5.70).
produto(mercadoCompreBem, queijo, 8.10).
produto(mercadoCompreBem, manteiga, 4.60).
produto(mercadoCompreBem, cafe, 7.20).
produto(mercadoCompreBem, alface, 3.20).
produto(mercadoCompreBem, cenoura, 2.80).
produto(mercadoCompreBem, batata, 4.10).
produto(mercadoCompreBem, laranja, 3.90).
produto(mercadoCompreBem, acucar, 3.50).
produto(mercadoCompreBem, oleo, 5.80).
produto(mercadoCompreBem, cebola, 2.70).
produto(mercadoCompreBem, sal, 1.10).
produto(mercadoCompreBem, alho, 2.40).
produto(mercadoCompreBem, pimentao, 2.90).
produto(mercadoCompreBem, peixe, 18.00).
produto(mercadoCompreBem, frango, 12.00).
produto(mercadoCompreBem, linguiça, 9.00).
produto(mercadoCompreBem, polvilho_doce, 7.00).
produto(mercadoCompreBem, queijo_minas, 15.00).
produto(mercadoCompreBem, farinha, 4.50).
produto(mercadoCompreBem, chocolate, 5.00).
produto(mercadoCompreBem, leite_condensado, 4.00).
produto(mercadoCompreBem, chocolate_po, 3.50).
produto(mercadoCompreBem, granulado, 2.50).
produto(mercadoCompreBem, massa_folhada, 6.00).
produto(mercadoCompreBem, alho_poro, 3.50).
produto(mercadoCompreBem, creme_leite, 3.00).
produto(mercadoCompreBem, carne_moida, 22.00).
produto(mercadoCompreBem, frango_desfiado, 14.00).
produto(mercadoCompreBem, milho, 2.20).
produto(mercadoCompreBem, ervilha, 2.00).
produto(mercadoCompreBem, caldo_galinha, 1.50).
produto(mercadoCompreBem, farinha_trigo, 3.00).
produto(mercadoCompreBem, farofa, 4.00).
produto(mercadoCompreBem, coco_ralado, 3.50).
produto(mercadoCompreBem, acucar, 2.00).
produto(mercadoCompreBem, salsa, 1.80).
produto(mercadoCompreBem, maracuja, 6.00).
produto(mercadoCompreBem, gelatina, 2.50).
produto(mercadoCompreBem, mandioca, 2.50).
produto(mercadoCompreBem, queijo_parmesao, 10.00).
produto(mercadoCompreBem, arroz_arboreo, 6.00).
produto(mercadoCompreBem, cogumelos, 12.00).
produto(mercadoCompreBem, caldo_legumes, 2.50).
produto(mercadoCompreBem, massa_lasanha, 7.00).
produto(mercadoCompreBem, presunto, 6.00).
produto(mercadoCompreBem, palmito, 5.00).
produto(mercadoCompreBem, sardinha, 4.00).
produto(mercadoCompreBem, pao, 2.50).
produto(mercadoCompreBem, leite_de_coco, 3.00).
produto(mercadoCompreBem, azeite_de_dende, 5.50).
produto(mercadoCompreBem, camarão, 18.00).
produto(mercadoCompreBem, amendoim, 7.00).



:- dynamic produto/3.

% Função para listar produtos de um mercado
listar_produtos_mercado :-
    write('Digite o nome do mercado: '), nl,
    read(Mercado),
    ( produto(Mercado, _, _) ->
        findall((Produto, Preco), produto(Mercado, Produto, Preco), ListaProdutos),
        imprimir_cor(azul, 'Produtos do mercado '), write(Mercado), nl,
        listar_produtos(ListaProdutos)
    ;
        write('Mercado não encontrado!'), nl
    ).

% Função auxiliar para imprimir a lista de produtos
listar_produtos([]).
listar_produtos([(Produto, Preco)|T]) :-
    write('- Produto: '), write(Produto), write(', Preço: '), write(Preco), nl,
    listar_produtos(T).


% Predicado auxiliar para verificar se um produto já está cadastrado em um mercado
produto_existe(Mercado, Produto) :-
    produto(Mercado, Produto, _).

% Função para cadastrar produtos
cadastrar_produto :-
    write('Digite o nome do mercado: '), nl,
    read(Mercado),
    write('Digite o nome do produto: '), nl,
    read(Produto),
    ( produto_existe(Mercado, Produto) ->
        write('Produto já cadastrado nesse mercado!'), nl
    ;
        write('Digite o preço do produto: '), nl,
        read(Preco),
        assertz(produto(Mercado, Produto, Preco)),
        write('Produto cadastrado com sucesso!'), nl
    ).

% Encontra o mercado mais barato para cada produto
encontrar_produtos_mais_baratos :-
    findall((Produto, Preco, Mercado), produto(Mercado, Produto, Preco), ListaProdutos),
    agrupar_por_produto(ListaProdutos, ProdutosAgrupados),
    encontrar_mais_baratos(ProdutosAgrupados, ProdutosMaisBaratos),
    mostrar_produtos_mais_baratos(ProdutosMaisBaratos).

% Agrupa produtos pelo seu nome
agrupar_por_produto(ListaProdutos, ProdutosAgrupados) :-
    setof(Produto, Preco^Mercado^member((Produto, Preco, Mercado), ListaProdutos), Produtos),
    agrupar(Produtos, ListaProdutos, ProdutosAgrupados).

agrupar([], _, []).
agrupar([Produto|RestoProdutos], ListaProdutos, [(Produto, Produtos)|Agrupados]) :-
    findall((Preco, Mercado), member((Produto, Preco, Mercado), ListaProdutos), Produtos),
    agrupar(RestoProdutos, ListaProdutos, Agrupados).

% Encontra o produto mais barato de cada grupo
encontrar_mais_baratos([], []).
encontrar_mais_baratos([(Produto, Produtos)|Resto], [(Produto, Preco, Mercado)|MaisBaratos]) :-
    sort(Produtos, [(Preco, Mercado)|_]),
    encontrar_mais_baratos(Resto, MaisBaratos).

% Mostra os produtos mais baratos
mostrar_produtos_mais_baratos([]).
mostrar_produtos_mais_baratos([(Produto, Preco, Mercado)|Resto]) :-
    format('Produto: ~w, Mercado: ~w, Preço: R$~2f~n', [Produto, Mercado, Preco]),
    listar_pratos_por_produto(Produto), nl,
    mostrar_produtos_mais_baratos(Resto).
