% Definição dos supermercados e sua reputação
supermercado(mercadoDoPovo, 8).
supermercado(mercadoBomPreco, 7).
supermercado(mercadoEconomico, 6).
supermercado(mercadoPopular, 5).
supermercado(mercadoSaoJoao, 4).
supermercado(mercadoCentral, 3).
supermercado(mercadoNovaEra, 2).
supermercado(mercadoCidade, 1).
supermercado(mercadoEstrela, 9).
supermercado(mercadoSantaLuzia, 10).
supermercado(mercadoSuperMais, 4).
supermercado(mercadoFamilia, 5).
supermercado(mercadoAlvorada, 6).
supermercado(mercadoPrata, 7).
supermercado(mercadoVitoria, 8).
supermercado(mercadoPremium, 9).
supermercado(mercadoElite, 10).
supermercado(mercadoDestaque, 3).
supermercado(mercadoReal, 2).
supermercado(mercadoCompreBem, 1).